Repository Suwon-University-Community-SUCAT/Sucat-BE-Server, pull requests merged in 2024-07, with the labels that each got.

#1 feat/refactor: Access Token 재발급 코드 개발, 공통 모듈 리팩토링
  src/main/java/com/Sucat/domain/token/controller/TokenController.java
  src/main/java/com/Sucat/domain/token/exception/TokenException.java
  src/main/java/com/Sucat/domain/token/model/RefreshToken.java
  src/main/java/com/Sucat/domain/token/model/TokenResponse.java
  src/main/java/com/Sucat/domain/token/repository/RefreshTokenRepository.java
  src/main/java/com/Sucat/domain/token/service/TokenService.java
  src/main/java/com/Sucat/domain/user/controller/UserController.java
  src/main/java/com/Sucat/domain/user/dto/UserDto.java
  src/main/java/com/Sucat/domain/user/exception/UserException.java
  src/main/java/com/Sucat/domain/user/model/User.java
  src/main/java/com/Sucat/domain/user/repository/UserRepository.java
  src/main/java/com/Sucat/domain/user/service/UserService.java
  src/main/java/com/Sucat/global/common/code/BaseCode.java
  src/main/java/com/Sucat/global/common/code/ErrorCode.java
  src/main/java/com/Sucat/global/common/code/SuccessCode.java
  src/main/java/com/Sucat/global/common/constant/ConstraintConstants.java
  src/main/java/com/Sucat/global/common/constant/EmailConstants.java
  src/main/java/com/Sucat/global/common/constant/SwaggerConstants.java
  src/main/java/com/Sucat/global/common/dto/ErrorReasonDto.java
  src/main/java/com/Sucat/global/common/dto/ReasonDto.java
  src/main/java/com/Sucat/global/common/response/ApiResponse.java
  src/main/java/com/Sucat/global/config/SecurityConfig.java
  src/main/java/com/Sucat/global/config/SwaggerConfig.java
  src/main/java/com/Sucat/global/error/ErrorResponse.java
  src/main/java/com/Sucat/global/error/GlobalExceptionHandler.java
  src/main/java/com/Sucat/global/error/exception/BusinessException.java
  src/main/java/com/Sucat/global/error/exception/EntityNotFoundException.java
  src/main/java/com/Sucat/global/error/exception/InvalidValueException.java
  src/main/java/com/Sucat/global/infra/email/api/EmailController.java
  src/main/java/com/Sucat/global/infra/email/dto/EmailRequest.java
  src/main/java/com/Sucat/global/infra/email/dto/VerificationCode.java
  src/main/java/com/Sucat/global/infra/email/repository/VerificationCodeRepository.java
  src/main/java/com/Sucat/global/infra/email/service/EmailSendService.java
  src/main/java/com/Sucat/global/jwt/model/JwtToken.java
  src/main/java/com/Sucat/global/security/filter/JsonUsernamePasswordAuthenticationFilter.java
  src/main/java/com/Sucat/global/security/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/Sucat/global/security/handler/LoginFailureHandler.java
  src/main/java/com/Sucat/global/security/handler/LoginSuccessJWTProvideHandler.java
  src/main/java/com/Sucat/global/security/service/UserDetailsServiceImpl.java
  src/main/java/com/Sucat/global/util/JwtUtil.java
  src/main/java/com/Sucat/global/util/JwtUtilImpl.java
  src/test/java/com/Sucat/global/jwt/service/JwtFilterAuthenticationTest.java
  src/test/java/com/Sucat/global/jwt/service/jwtServiceTest.java
Labels: ✅ Test, ✨ Feature, 🔨 Refactor

#2 feat: 비밀번호 관련 로직 개발
  src/main/java/com/Sucat/domain/token/controller/TokenController.java
  src/main/java/com/Sucat/domain/token/service/TokenService.java
  src/main/java/com/Sucat/domain/user/controller/AuthController.java
  src/main/java/com/Sucat/domain/user/controller/UserController.java
  src/main/java/com/Sucat/domain/user/dto/UserDto.java
  src/main/java/com/Sucat/domain/user/model/User.java
  src/main/java/com/Sucat/domain/user/service/AuthService.java
  src/main/java/com/Sucat/domain/user/service/UserService.java
  src/main/java/com/Sucat/global/common/code/ErrorCode.java
  src/main/java/com/Sucat/global/common/code/SuccessCode.java
  src/main/java/com/Sucat/global/common/constant/ConstraintConstants.java
  src/main/java/com/Sucat/global/config/SecurityConfig.java
  src/main/java/com/Sucat/global/infra/email/api/EmailController.java
  src/main/java/com/Sucat/global/security/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/Sucat/global/util/JwtUtil.java
  src/main/java/com/Sucat/global/util/JwtUtilImpl.java
  src/test/java/com/Sucat/global/jwt/service/JwtFilterAuthenticationTest.java
  src/test/java/com/Sucat/global/jwt/service/LoginTest.java
Labels: ✅ Test, ✨ Feature, 🐞 BugFix, 🔨 Refactor

#3 feat/refactor: 이메일 인증 관련 코드 수정, 개발
  src/main/java/com/Sucat/global/common/code/ErrorCode.java
  src/main/java/com/Sucat/global/infra/email/api/EmailController.java
  src/main/java/com/Sucat/global/infra/email/dto/EmailRequest.java
  src/main/java/com/Sucat/global/infra/email/exception/EmailException.java
  src/main/java/com/Sucat/global/infra/email/model/VerificationCode.java
  src/main/java/com/Sucat/global/infra/email/repository/VerificationCodeRepository.java
  src/main/java/com/Sucat/global/infra/email/service/EmailSendService.java
Labels: ✨ Feature, 🔨 Refactor

#4 feat: 이미지 업로드, 사용자 프로필 업로드 기능 추가
  src/main/java/com/Sucat/domain/board/model/Board.java
  src/main/java/com/Sucat/domain/board/model/Images.java
  src/main/java/com/Sucat/domain/chatmessage/service/ImageService.java
  src/main/java/com/Sucat/domain/image/exception/ImageException.java
  src/main/java/com/Sucat/domain/image/model/Image.java
  src/main/java/com/Sucat/domain/user/controller/AuthController.java
  src/main/java/com/Sucat/domain/user/model/User.java
  src/main/java/com/Sucat/domain/user/service/AuthService.java
  src/main/java/com/Sucat/global/common/code/ErrorCode.java
  src/main/java/com/Sucat/global/config/SecurityConfig.java
Labels: ✨ Feature, 🔨 Refactor

#5 refactor: 이미지 객체 생성에 따른 프로피 변경 로직 수정
  src/main/java/com/Sucat/domain/image/model/Image.java
  src/main/java/com/Sucat/domain/image/service/ImageService.java
  src/main/java/com/Sucat/domain/user/controller/UserController.java
  src/main/java/com/Sucat/domain/user/dto/UserDto.java
  src/main/java/com/Sucat/domain/user/model/User.java
  src/main/java/com/Sucat/domain/user/repository/UserQueryRepository.java
  src/main/java/com/Sucat/domain/user/service/AuthService.java
  src/main/java/com/Sucat/domain/user/service/UserService.java
  src/main/java/com/Sucat/global/error/GlobalExceptionHandler.java
  src/main/java/com/Sucat/global/security/filter/JwtAuthenticationProcessingFilter.java
Labels: 🔨 Refactor

#6 feat: 공지사항에 대한 기능 개발
  src/main/java/com/Sucat/domain/image/model/Image.java
  src/main/java/com/Sucat/domain/image/service/ImageService.java
  src/main/java/com/Sucat/domain/notice/model/Notification.java
  src/main/java/com/Sucat/domain/notification/controller/NotificationController.java
  src/main/java/com/Sucat/domain/notification/dto/NotificationDto.java
  src/main/java/com/Sucat/domain/notification/model/Notification.java
  src/main/java/com/Sucat/domain/notification/repository/NotificationRepository.java
  src/main/java/com/Sucat/domain/notification/service/NotificationService.java
  src/main/java/com/Sucat/domain/user/controller/AuthController.java
  src/main/java/com/Sucat/domain/user/model/User.java
  src/main/java/com/Sucat/domain/user/repository/UserRepository.java
  src/main/java/com/Sucat/domain/user/service/AuthService.java
  src/main/java/com/Sucat/domain/user/service/UserService.java
  src/main/java/com/Sucat/global/common/constant/ConstraintConstants.java
  src/main/java/com/Sucat/global/config/SecurityConfig.java
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor

#7 feat/test: 공지사항 상세 페이지 개발, 테스트 코드 수정
  src/main/java/com/Sucat/domain/notification/controller/NotificationController.java
  src/main/java/com/Sucat/domain/notification/dto/NotificationDto.java
  src/main/java/com/Sucat/domain/notification/exception/NotificationException.java
  src/main/java/com/Sucat/domain/notification/repository/NotificationQueryRepository.java
  src/main/java/com/Sucat/domain/notification/service/NotificationService.java
  src/main/java/com/Sucat/global/common/code/ErrorCode.java
  src/test/java/com/Sucat/global/jwt/service/JwtFilterAuthenticationTest.java
Labels: ✅ Test, ✨ Feature

#8 refactor: 회원 프로필에 대한 에러 해결, GlobalExceptionHandler에 메서드 추가
  src/main/java/com/Sucat/domain/user/controller/UserController.java
  src/main/java/com/Sucat/domain/user/dto/UserDto.java
  src/main/java/com/Sucat/domain/user/model/User.java
  src/main/java/com/Sucat/domain/user/service/UserService.java
  src/main/java/com/Sucat/global/common/code/ErrorCode.java
  src/main/java/com/Sucat/global/config/SecurityConfig.java
  src/main/java/com/Sucat/global/error/GlobalExceptionHandler.java
Labels: 🔨 Refactor

#9 feat/refactor: 친구 추가 관련 로직 개발
  src/main/java/com/Sucat/domain/friendship/controller/FriendShipController.java
  src/main/java/com/Sucat/domain/friendship/dto/WaitingFriendDto.java
  src/main/java/com/Sucat/domain/friendship/exception/FriendShipException.java
  src/main/java/com/Sucat/domain/friendship/model/FriendShip.java
  src/main/java/com/Sucat/domain/friendship/model/FriendshipStatus.java
  src/main/java/com/Sucat/domain/friendship/repository/FriendShipQueryRepository.java
  src/main/java/com/Sucat/domain/friendship/repository/FriendShipRepository.java
  src/main/java/com/Sucat/domain/friendship/service/FriendShipService.java
  src/main/java/com/Sucat/domain/notification/controller/NotificationController.java
  src/main/java/com/Sucat/domain/user/model/User.java
  src/main/java/com/Sucat/domain/user/service/UserService.java
  src/main/java/com/Sucat/global/common/code/ErrorCode.java
Labels: ✨ Feature, 🔨 Refactor

#10 feat/fix: 친구 목록 조회 개발, 친구 요청 수락, 거절 개발
  src/main/java/com/Sucat/domain/friendship/controller/FriendShipController.java
  src/main/java/com/Sucat/domain/friendship/dto/AcceptFriendDto.java
  src/main/java/com/Sucat/domain/friendship/repository/FriendShipQueryRepository.java
  src/main/java/com/Sucat/domain/friendship/service/FriendShipService.java
  src/main/java/com/Sucat/domain/token/repository/RefreshTokenRepository.java
  src/main/java/com/Sucat/domain/token/service/TokenService.java
  src/main/java/com/Sucat/domain/user/controller/AuthController.java
  src/main/java/com/Sucat/domain/user/dto/UserDto.java
  src/main/java/com/Sucat/domain/user/service/AuthService.java
  src/main/java/com/Sucat/global/common/code/ErrorCode.java
  src/main/java/com/Sucat/global/config/SecurityConfig.java
  src/main/java/com/Sucat/global/util/JwtUtilImpl.java
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor

#11 Test
  src/main/java/com/Sucat/HomeController.java
Labels: ✨ Feature

#12 refactor: Admin 계정은 토큰의 만료 기한을 무한정으로 설정
  src/main/java/com/Sucat/domain/user/model/UserRole.java
  src/main/java/com/Sucat/global/config/SecurityConfig.java
  src/main/java/com/Sucat/global/security/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/Sucat/global/security/handler/LoginSuccessJWTProvideHandler.java
  src/main/java/com/Sucat/global/util/JwtUtil.java
  src/main/java/com/Sucat/global/util/JwtUtilImpl.java
Labels: 🔨 Refactor

#13 feat/refactor: 채팅방 - 메시지 기능 개발
  build.gradle
  src/main/java/com/Sucat/domain/chatmessage/controller/MessageController.java
  src/main/java/com/Sucat/domain/chatmessage/dto/MessageDto.java
  src/main/java/com/Sucat/domain/chatmessage/dto/MessageResponse.java
  src/main/java/com/Sucat/domain/chatmessage/model/ChatMessage.java
  src/main/java/com/Sucat/domain/chatmessage/model/MessageType.java
  src/main/java/com/Sucat/domain/chatmessage/repository/MessageRepository.java
  src/main/java/com/Sucat/domain/chatmessage/service/ChatService.java
  src/main/java/com/Sucat/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/Sucat/domain/chatroom/dto/ChatRoomDto.java
  src/main/java/com/Sucat/domain/chatroom/exception/ChatRoomException.java
  src/main/java/com/Sucat/domain/chatroom/model/ChatRoom.java
  src/main/java/com/Sucat/domain/chatroom/repository/RoomRepository.java
  src/main/java/com/Sucat/domain/chatroom/service/ChatRoomService.java
  src/main/java/com/Sucat/domain/user/dto/UserDto.java
  src/main/java/com/Sucat/domain/user/model/User.java
  src/main/java/com/Sucat/domain/user/service/UserService.java
  src/main/java/com/Sucat/global/common/code/ErrorCode.java
  src/main/java/com/Sucat/global/common/response/PageInfo.java
  src/main/java/com/Sucat/global/config/RedisConfig.java
  src/main/java/com/Sucat/global/config/SecurityConfig.java
  src/main/java/com/Sucat/global/config/WebSocketConfig.java
  src/main/java/com/Sucat/global/redis/PublishMessage.java
  src/main/java/com/Sucat/global/redis/RedisController.java
  src/main/java/com/Sucat/global/redis/RedisSubscriber.java
  src/main/java/com/Sucat/global/security/handler/JwtHandshakeInterceptor.java
  src/main/java/com/Sucat/global/util/JwtUtilImpl.java
  src/main/java/com/Sucat/global/websocket/handler/WebSockChatHandler.java
  src/test/java/com/Sucat/chat/MessageControllerTest.java
  src/test/java/com/Sucat/chat/MessageControllerWebSocketTest.java
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor

#14 refactor: roomId를 별도로 생성한 식별자로 변경
  src/main/java/com/Sucat/domain/chatmessage/controller/MessageController.java
  src/main/java/com/Sucat/domain/chatmessage/dto/MessageDto.java
  src/main/java/com/Sucat/domain/chatmessage/service/ChatService.java
  src/main/java/com/Sucat/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/Sucat/domain/chatroom/model/ChatRoom.java
  src/main/java/com/Sucat/domain/chatroom/repository/RoomRepository.java
  src/main/java/com/Sucat/domain/chatroom/service/ChatRoomService.java
  src/main/java/com/Sucat/global/redis/PublishMessage.java
  src/test/java/com/Sucat/chat/MessageControllerTest.java
  src/test/java/com/Sucat/chat/MessageControllerWebSocketTest.java
Labels: 🔨 Refactor

#16 refactor: 트랜잭션 처리, 코드 수정
  src/main/java/com/Sucat/domain/chatmessage/service/ChatService.java
  src/main/java/com/Sucat/domain/chatroom/service/ChatRoomService.java
  src/main/java/com/Sucat/domain/friendship/service/FriendShipService.java
  src/main/java/com/Sucat/domain/image/service/ImageService.java
Labels: 🔨 Refactor

#17 feat/refactor: 친구, 채팅 관련 기능 개발 및 공통 응답 모듈 리팩토링
  src/main/java/com/Sucat/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/Sucat/domain/chatroom/dto/ChatRoomDto.java
  src/main/java/com/Sucat/domain/chatroom/repository/RoomRepository.java
  src/main/java/com/Sucat/domain/chatroom/service/ChatRoomService.java
  src/main/java/com/Sucat/domain/friendship/controller/FriendShipController.java
  src/main/java/com/Sucat/domain/friendship/dto/AcceptFriendDto.java
  src/main/java/com/Sucat/domain/friendship/dto/WaitingFriendDto.java
  src/main/java/com/Sucat/domain/friendship/model/FriendShip.java
  src/main/java/com/Sucat/domain/friendship/repository/FriendShipQueryRepository.java
  src/main/java/com/Sucat/domain/friendship/repository/FriendShipRepository.java
  src/main/java/com/Sucat/domain/friendship/service/FriendShipService.java
  src/main/java/com/Sucat/domain/user/dto/UserDto.java
  src/main/java/com/Sucat/domain/user/model/User.java
  src/main/java/com/Sucat/domain/user/service/UserService.java
  src/main/java/com/Sucat/global/common/code/ErrorCode.java
  src/main/java/com/Sucat/global/common/response/ApiResponse.java
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor

#18 refactor: image 처리 서비스 리팩토링, 반환 값 변경
  src/main/java/com/Sucat/domain/chatroom/dto/ChatRoomDto.java
  src/main/java/com/Sucat/domain/friendship/dto/AcceptFriendDto.java
  src/main/java/com/Sucat/domain/friendship/dto/WaitingFriendDto.java
  src/main/java/com/Sucat/domain/image/model/Image.java
  src/main/java/com/Sucat/domain/image/service/ImageService.java
  src/main/java/com/Sucat/domain/notification/dto/NotificationDto.java
  src/main/java/com/Sucat/domain/notification/service/NotificationService.java
  src/main/java/com/Sucat/domain/user/dto/UserDto.java
  src/main/java/com/Sucat/domain/user/service/AuthService.java
  src/main/java/com/Sucat/domain/user/service/UserService.java
  src/main/java/com/Sucat/global/common/code/ErrorCode.java
Labels: 🔨 Refactor

#19 feat: SSE를 이용한 알림 기능 개발
  src/main/java/com/Sucat/domain/friendship/repository/FriendShipQueryRepository.java
  src/main/java/com/Sucat/domain/friendship/service/FriendShipService.java
  src/main/java/com/Sucat/domain/notify/annotation/NeedNotify.java
  src/main/java/com/Sucat/domain/notify/aop/NotifyAspect.java
  src/main/java/com/Sucat/domain/notify/aop/proxy/NotifyInfo.java
  src/main/java/com/Sucat/domain/notify/controller/NotifyController.java
  src/main/java/com/Sucat/domain/notify/dto/NotifyDto.java
  src/main/java/com/Sucat/domain/notify/dto/NotifyMessage.java
  src/main/java/com/Sucat/domain/notify/model/Notify.java
  src/main/java/com/Sucat/domain/notify/model/NotifyType.java
  src/main/java/com/Sucat/domain/notify/repository/EmitterRepository.java
  src/main/java/com/Sucat/domain/notify/repository/EmitterRepositoryImpl.java
  src/main/java/com/Sucat/domain/notify/repository/NotifyRepository.java
  src/main/java/com/Sucat/domain/notify/service/NotifyService.java
  src/main/java/com/Sucat/domain/user/model/User.java
  src/main/java/com/Sucat/global/util/JwtUtil.java
  src/main/java/com/Sucat/global/util/JwtUtilImpl.java
Labels: ✨ Feature

#20 feat: 알림 추가 기능 개발
  src/main/java/com/Sucat/domain/image/service/ImageService.java
  src/main/java/com/Sucat/domain/notify/controller/NotifyController.java
  src/main/java/com/Sucat/domain/notify/dto/NotifyDto.java
  src/main/java/com/Sucat/domain/notify/exception/NotifyException.java
  src/main/java/com/Sucat/domain/notify/model/Notify.java
  src/main/java/com/Sucat/domain/notify/repository/NotifyQueryRepository.java
  src/main/java/com/Sucat/domain/notify/repository/NotifyQueryRepositoryImpl.java
  src/main/java/com/Sucat/domain/notify/repository/NotifyRepository.java
  src/main/java/com/Sucat/domain/notify/service/NotifyService.java
  src/main/java/com/Sucat/global/common/code/ErrorCode.java
Labels: ✨ Feature, 🐞 BugFix
