Repository Suwon-University-Community-SUCAT/Sucat-BE-Server, pull requests merged in 2024-08, with the labels that each got.

#23 refactor: Get 요청의 경우 데이터를 param으로 받도록 수정
  src/main/java/com/Sucat/domain/user/controller/AuthController.java
  src/main/java/com/Sucat/domain/user/controller/UserController.java
  src/main/java/com/Sucat/domain/user/dto/UserDto.java
  src/main/java/com/Sucat/domain/user/service/AuthService.java
Labels: 🐞 BugFix, 🔨 Refactor

#26 친구 검색 API 개발, 정렬이 필요한 API에 정렬 기능 추가 개발
  src/main/java/com/Sucat/domain/chatroom/controller/ChatRoomController.java
  src/main/java/com/Sucat/domain/chatroom/repository/RoomRepository.java
  src/main/java/com/Sucat/domain/chatroom/service/ChatRoomService.java
  src/main/java/com/Sucat/domain/friendship/controller/FriendShipController.java
  src/main/java/com/Sucat/domain/friendship/dto/FriendListResponse.java
  src/main/java/com/Sucat/domain/friendship/dto/FriendShipDto.java
  src/main/java/com/Sucat/domain/friendship/model/FriendShip.java
  src/main/java/com/Sucat/domain/friendship/repository/FriendShipQueryRepository.java
  src/main/java/com/Sucat/domain/friendship/repository/FriendShipRepository.java
  src/main/java/com/Sucat/domain/friendship/service/FriendShipService.java
Labels: ✨ Feature, 🔨 Refactor

#28 게시판 코드 리팩토링, 기능 개발
  src/main/java/com/Sucat/domain/board/DTO/BoardListResponseDTO.java
  src/main/java/com/Sucat/domain/board/DTO/BoardPostDTO.java
  src/main/java/com/Sucat/domain/board/DTO/BoardPostRequestDTO.java
  src/main/java/com/Sucat/domain/board/DTO/BoardResponse.java
  src/main/java/com/Sucat/domain/board/DTO/BoardUpdateRequestDTO.java
  src/main/java/com/Sucat/domain/board/DTO/ResponseDTO.java
  src/main/java/com/Sucat/domain/board/controller/BoardController.java
  src/main/java/com/Sucat/domain/board/dto/BoardDto.java
  src/main/java/com/Sucat/domain/board/exception/BoardException.java
  src/main/java/com/Sucat/domain/board/model/Board.java
  src/main/java/com/Sucat/domain/board/repository/BoardRepository.java
  src/main/java/com/Sucat/domain/board/service/BoardService.java
  src/main/java/com/Sucat/domain/comment/domain/Comment.java
  src/main/java/com/Sucat/domain/comment/dto/CommentPostDTO.java
  src/main/java/com/Sucat/domain/comment/dto/CommentPostResponse.java
  src/main/java/com/Sucat/domain/image/service/ImageService.java
  src/main/java/com/Sucat/global/common/code/ErrorCode.java
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor

#29 psm_dev
  src/main/java/com/Sucat/domain/board/controller/BoardController.java
  src/main/java/com/Sucat/domain/board/dto/BoardDto.java
  src/main/java/com/Sucat/domain/board/model/Board.java
  src/main/java/com/Sucat/domain/board/repository/BoardQueryRepository.java
  src/main/java/com/Sucat/domain/board/repository/BoardRepository.java
  src/main/java/com/Sucat/domain/board/service/BoardService.java
  src/main/java/com/Sucat/domain/notify/dto/NotifyDto.java
  src/main/java/com/Sucat/domain/user/controller/UserController.java
  src/main/java/com/Sucat/domain/user/dto/UserDto.java
  src/main/java/com/Sucat/domain/user/service/UserService.java
  src/main/java/com/Sucat/global/common/dao/BaseEntity.java
  src/main/java/com/Sucat/global/config/JacksonConfig.java
  src/main/java/com/Sucat/global/infra/email/model/VerificationCode.java
  src/main/java/com/Sucat/global/infra/email/service/EmailSendService.java
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor

#30 psm_dev
  src/main/java/com/Sucat/domain/board/dto/BoardDto.java
  src/main/java/com/Sucat/domain/board/model/Board.java
  src/main/java/com/Sucat/domain/scrap/controller/ScrapController.java
  src/main/java/com/Sucat/domain/scrap/model/Scrap.java
  src/main/java/com/Sucat/domain/scrap/repository/ScrapRepository.java
  src/main/java/com/Sucat/domain/scrap/service/ScrapService.java
  src/main/java/com/Sucat/domain/user/model/User.java
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor

#31 comment_areum
  src/main/java/com/Sucat/domain/comment/controller/CommentController.java
  src/main/java/com/Sucat/domain/comment/domain/Comment.java
  src/main/java/com/Sucat/domain/comment/dto/CommentPostDTO.java
  src/main/java/com/Sucat/domain/comment/dto/CommentPostResponse.java
  src/main/java/com/Sucat/domain/comment/repository/CommentRepository.java
  src/main/java/com/Sucat/domain/comment/service/CommentService.java
Labels: ✨ Feature

#32 feat/refactor: 댓글 기능 개발 및 리팩토링, 버그 수정
  src/main/java/com/Sucat/domain/board/dto/BoardDto.java
  src/main/java/com/Sucat/domain/board/model/Board.java
  src/main/java/com/Sucat/domain/board/service/BoardService.java
  src/main/java/com/Sucat/domain/comment/controller/CommentController.java
  src/main/java/com/Sucat/domain/comment/domain/Comment.java
  src/main/java/com/Sucat/domain/comment/dto/CommentDto.java
  src/main/java/com/Sucat/domain/comment/dto/CommentPostDTO.java
  src/main/java/com/Sucat/domain/comment/dto/CommentPostResponse.java
  src/main/java/com/Sucat/domain/comment/exception/CommentException.java
  src/main/java/com/Sucat/domain/comment/service/CommentService.java
  src/main/java/com/Sucat/domain/scrap/service/ScrapService.java
  src/main/java/com/Sucat/domain/user/model/User.java
  src/main/java/com/Sucat/global/common/code/ErrorCode.java
  src/main/java/com/Sucat/global/config/SecurityConfig.java
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor

#34 게시물 관련 기능 개발, 좋아요 기능(게시물, 댓글) 개발
  src/main/java/com/Sucat/domain/board/controller/BoardController.java
  src/main/java/com/Sucat/domain/board/dto/BoardDto.java
  src/main/java/com/Sucat/domain/board/model/Board.java
  src/main/java/com/Sucat/domain/board/service/BoardService.java
  src/main/java/com/Sucat/domain/comment/domain/Comment.java
  src/main/java/com/Sucat/domain/comment/dto/CommentDto.java
  src/main/java/com/Sucat/domain/comment/service/CommentService.java
  src/main/java/com/Sucat/domain/like/controller/BoardLikeController.java
  src/main/java/com/Sucat/domain/like/controller/CommentLikeController.java
  src/main/java/com/Sucat/domain/like/model/BoardLike.java
  src/main/java/com/Sucat/domain/like/model/CommentLike.java
  src/main/java/com/Sucat/domain/like/repository/BoardLikeRepository.java
  src/main/java/com/Sucat/domain/like/repository/CommentLikeRepository.java
  src/main/java/com/Sucat/domain/like/service/BoardLikeService.java
  src/main/java/com/Sucat/domain/like/service/CommentLikeService.java
  src/main/java/com/Sucat/domain/user/model/User.java
Labels: 📬 API, ✨ Feature, 🐞 BugFix, 🔨 Refactor
